cms_register/urls.py
from django.conf.urls import url

from . import views

app_name = 'cms_register'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginv, name='login'),
    url(r'^logout/$', views.logoutv, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^contests/$', views.contest_view, name='contests'),
    url(r'^ranking/(?P<contest_id>[0-9]+)/$', views.ranking, name='ranking'),
    url(r'^unranking/(?P<contest_id>[0-9]+)/$', views.unrank, name='unranking'),
]

registration_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('cms_register.urls', namespace="cms_register")),
    url(r'^sc/', include('scoreboard.urls')),
]

scoreboard/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

cms_register/models.py
import uuid
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from ordered_model.models import OrderedModel


# Create your models here.
class Announcement(OrderedModel):
    def __str__(self):
        return self.announce_text

    announce_text = models.CharField(max_length=2000)

    class Meta(OrderedModel.Meta):
        pass


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "rankings_txt/%s.%s" % (uuid.uuid4(), ext)
    return filename


class Contest(models.Model):
    def __str__(self):
        return self.contest_name

    contest_name = models.CharField(max_length=2000)
    start_time = models.DateTimeField('Start')
    duration = models.DurationField()
    contest_time = models.DurationField(default=timedelta(0))
    cms_id = models.IntegerField(default=0)
    ranking_file = models.FileField(upload_to=get_file_path, blank=True)
    unofficial_ranking_file = models.FileField(upload_to=get_file_path, blank=True)
    contest_url = models.CharField(max_length=2000, default='#')

    def reg_count(self):
        return self.participant_set.count()


class Participant(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Contestant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    grade = models.CharField(max_length=2000, default='-')
    school = models.CharField(max_length=2000, default='-')

cms_register/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 

import collections
import json
import locale
import re
import subprocess
import urllib
from functools import cmp_to_key

import jdatetime
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaulttags import register
from django.utils import timezone

from cms_register.utils import password_check, persian_num, comp
from .models import Announcement, Contest, Participant


# Create your views here.


def index(request):
    All = Announcement.objects.all()
    return render(request, "cms_register/index.html", {'Announce': All})


def loginv(request):
    usern = None
    passw = None
    ok = False
    if request.method == 'POST':
        usern = request.POST['username']
        passw = request.POST['password']
        ok = True
    user = authenticate(username=usern, password=passw)
    if user is not None or request.user.is_authenticated:
        login(request, user)
        return redirect('cms_register:index')
    else:
        return render(request, "cms_register/login.html", {'Error': ok})


def logoutv(request):
    logout(request)
    return redirect('cms_register:index')


def profile(request):
    return register(request, 1)


def register(request, x=0):
    info = collections.OrderedDict()
    error = {}
    done = False
    cap_error = False

    def getInfo(field):
        if field in request.POST and request.POST[field] != '':
            return request.POST[field]
        else:
            return None

    def addError(field, val):
        if error[field] == '':
            error[field] = val

    if request.user.is_authenticated and not x:
        return redirect('cms_register:index')
    if not request.user.is_authenticated and x:
        return redirect('cms_register:index')
    fields = ['username', 'email', 'password', 'password2', 'name', 'lname']
    place = {'username': 'نام کاربری',
             'email': 'رایانامه',
             'password': 'رمزعبور',
             'password2': 'تکرار رمزعبور',
             'name': 'نام',
             'lname': 'نام خانوادگی',
             # 'grade' : 'پایه',
             # 'school' : 'مدرسه',
             }
    types = {'username': 'text',
             'email': 'email',
             'password': 'password',
             'password2': 'password',
             'name': 'text',
             'lname': 'text',
             # 'grade' : 'text',
             # 'school' : 'text',
             }
    for field in fields:
        error[field] = ''
        info[field] = ''
    if x:
        info['username'] = request.user.username
        info['name'] = request.user.first_name
        info['lname'] = request.user.last_name
        info['email'] = request.user.email
    if request.method == 'POST':
        for field in fields:
            if getInfo(field) == None:
                if not x or (field != 'password' and field != 'password2' and field != 'username'):
                    addError(field, 'این فیلد لازم است.')
            else:
                info[field] = getInfo(field)
        if x:
            info['username'] = request.user.username
        if len(info['username']) > 150:
            addError('username', 'حداکثر ۱۵۰ کاراکتر')
        if not re.match("^[A-Za-z0-9_-]+$", info['username']):
            addError('username', 'تنها حروف انگلیسی، ارقام، خط تیره و آندرلاین مجاز است.')
        if not x and User.objects.filter(username=info['username']).exists():
            addError('username', 'این نام کاربری انتخاب شده است.')
        if not re.match(r"[^@]+@[^@]+\.[^@]+", info['email']):
            addError('email', 'ایمیل معتبر وارد کنید.')
        if info['password'] != '' or info['password2'] != '':
            passdet = password_check(info['password'])
            if passdet['length_error']:
                addError('password', 'حداقل ۸ کاراکتر ضروری است.')
            if passdet['digit_error']:
                addError('password', 'حداقل یک کاراکتر رقم ضروری است.')
            if passdet['lowercase_error'] and passdet['uppercase_error']:
                addError('password', 'حداقل یک حرف لاتین ضروری است.')
            if info['password'] != info['password2']:
                addError('password2', 'با رمز عبور مطابقت ندارد.')
        if not re.match(r"^[a-zA-Z ]+$", info['name']):
            addError('name', 'نام خود را انگلیسی وارد کنید.(حروف و فاصله)')
        if not re.match(r"^[a-zA-Z ]+$", info['lname']):
            addError('lname', 'نام خانوادگی خود را انگلیسی وارد کنید.(حروف و فاصله)')
        ok = True
        for key in error:
            if error[key] != '':
                ok = False;
        values = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': request.POST.get(u'g-recaptcha-response', None),
            'remoteip': request.META.get("REMOTE_ADDR", None),
        }
        url = settings.RECAPTCHA_REQUEST_URL
        data = urllib.parse.urlencode(values)
        binary_data = data.encode('UTF-8')
        req = urllib.request.Request(url, binary_data)
        resp = urllib.request.urlopen(req)
        strfeedback = resp.read().decode('UTF-8')
        res = json.loads(strfeedback)
        if not res['success']:
            ok = True#False
            cap_error = False#True;
        if ok and not x:
            user = User.objects.create_user(info['username'], info['email'], info['password'])
            user.first_name = info['name']
            user.last_name = info['lname']
            # user.contestant.grade = info['grade']
            # user.contestant.school = info['school']
            user.save()
            res = subprocess.call(
                ['cmsAddUser', '-p', info['password'], '-e', info['email'], info['name'], info['lname'],
                 info['username']])
            if not res:
                subprocess.call(
                    ['python', 'python/EditUser.py', '-p', info['password'], '-e', info['email'], '-fn', info['name'],
                     '-ln', info['lname'], info['username']])
            done = True
        if ok and x:
            user = User.objects.get(username=info['username'])
            user.first_name = info['name']
            user.last_name = info['lname']
            user.email = info['email']
            if info['password'] != '':
                user.set_password(info['password'])
                subprocess.call(
                    ['python', 'python/EditUser.py', '-p', info['password'], '-e', info['email'], '-fn', info['name'],
                     '-ln', info['lname'], info['username']])
            else:
                subprocess.call(
                    ['python', 'python/EditUser.py', '-e', info['email'], '-fn', info['name'], '-ln', info['lname'],
                     info['username']])
            user.save()
            done = True
    info['password'] = info['password2'] = ''
    return render(request, "cms_register/register.html",
                  {'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY, 'ok': done, 'info': info, 'error': error,
                   'place': place, 'type': types, 'caper': cap_error, 'x': x})


def format_timedelta(td, type):
    days = td.days
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    days, hours, minutes, seconds = int(days), int(hours), int(minutes), int(seconds)
    if type != 2:
        if hours < 10:
            hours = '0%s' % int(hours)
        if minutes < 10:
            minutes = '0%s' % minutes
        if seconds < 10:
            seconds = '0%s' % seconds
        if type == 1:
            return '%s:%s' % (hours, minutes)
        else:
            return '%s:%s:%s' % (hours, minutes, seconds)
    if hours == 0:
        return '%s روز' % (days)
    return '%s روز و %s ساعت' % (days, hours)


def contest_view(request):
    done = False
    if request.method == 'POST' and request.user.is_authenticated and request.POST.get('register') == 'register':
        cid = request.POST.get('cid');
        con = Contest.objects.get(id=cid);
        if Participant.objects.filter(user=request.user, contest=con).count() == 0:
            partof = Participant(user=request.user, contest=con)
            partof.save()
            subprocess.call(['cmsAddParticipation', '-c', str(con.cms_id), request.user.username])
            done = True
    clist = Contest.objects.order_by('-start_time')
    date = {}
    time = {}
    expired = {}
    ended = {}
    registered = {}
    dur = {}
    need = {}
    cdown = {}
    #locale.setlocale(locale.LC_ALL, 'fa_IR')
    for contest in clist:
        cdown[contest.id] = max(0, int((contest.start_time - timezone.now() + contest.duration).total_seconds()))
        tmp = jdatetime.datetime.fromgregorian(datetime=timezone.localtime(contest.start_time))
        date[contest.id] = persian_num(tmp.strftime("%d %b %Y"))
        time[contest.id] = persian_num(tmp.strftime("%H:%M"))
        dur[contest.id] = persian_num(format_timedelta(contest.duration, 2))
        need[contest.id] = persian_num(format_timedelta(contest.contest_time, 1))
        expired[contest.id] = (timezone.now() > (contest.start_time + contest.duration))
        print(timezone.now())
        print(contest.start_time + contest.duration)
        ended[contest.id] = (timezone.now() > (contest.start_time + contest.contest_time))
        registered[contest.id] = False
        if request.user.is_authenticated and contest.participant_set.filter(user=request.user).count() > 0:
            registered[contest.id] = True
    return render(request, "cms_register/contests.html",
                  {'contests': clist, 'date': date, 'time': time, 'expired': expired, 'registered': registered,
                   'done': done, 'dur': dur, 'need': need, 'ended': ended, 'cdown': cdown})


def unrank(request, contest_id):
    return ranking(request, contest_id, True)

cms_register/templates/cms_register/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://code.jquery.com/jquery-3.2.0.min.js"></script>
    <script src="{% static 'cms_register/jquery.countdown.min.js' %}"></script>
	<script>
	function toPersianNum( num, dontTrim ) {
		var i = 0,
		dontTrim = dontTrim || false,
		num = dontTrim ? num.toString() : num.toString().trim(),
		len = num.length,
		res = '',
		pos,
		persianNumbers = typeof persianNumber == 'undefined' ?
			['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'] :
			persianNumbers;
		for (; i < len; i++)
			if (( pos = persianNumbers[num.charAt(i)] ))
				res += pos;
			else
				res += num.charAt(i);	
			return res;
	}
	</script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

		<title>شاززز - Shaazzz</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'cms_register/css/bootstrap.css' %}?v=89" rel="stylesheet">
    <link href="{% static 'cms_register/css/mine.css' %}?v=89" rel="stylesheet">
    <!-- Bootstrap RTL theme -->
    <link href="{% static 'cms_register/rtl/bootstrap-rtl.css' %}?v=89" rel="stylesheet">

		<style>
		</style>


		{% block header %}
		{% endblock %}

  </head>

  <body role="document">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><img src="{% static 'cms_register/logo.png' %}" style="margin-top: -0.5em !important"></a>
        </div>

          <ul class="nav navbar-nav">
            <li class="{% block contest %}{% endblock %}"><a href="{% url 'cms_register:contests' %}">مسابقات</a></li>
          </ul>
          

          <ul class="nav navbar-nav navbar-right flip">
							{% if request.user.is_authenticated %}
						<li class="dropdown">
								<a href="#" class="dropdown-toggle en-text" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {{ request.user.username }}  <span class="caret"></span></a>
								<ul class="dropdown-menu">
									{% if request.user.is_staff %}
									<li><a href="{% url 'admin:index' %}">مدیریت</a></li>
									<li role="separator" class="divider"></li>
									{% endif %}
									<li><a href="{% url 'cms_register:profile' %}">نمایه</a></li>
									<li><a href="{% url 'cms_register:logout' %}">خروج</a></li>
								</ul>
						</li>
							{% else %}
									<li class="{% block login %}{% endblock %}"><a href="{% url 'cms_register:login' %}">ورود</a></li>
									<li class="{% block reg %}{% endblock %}"><a href="{% url 'cms_register:register' %}">ثبت نام</a></li>
							{% endif %}
						</li>
          </ul>
      </div><!-- /.container-fluid -->
    </nav>


		<div class="jumbotron">
      {% block content %}
			{% endblock %}
    </div>

		<footer class="footer">
      <div class="container">
        <p class="text-muted">تمامی حقوق برای <a href="http://shaazzz.ir">شاززز</a> محفوظ است.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'cms_register/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
      $('button').popover();
    </script>
  </body>
</html>

cms_register/templates/cms_register/contests.html
{% extends 'cms_register/base.html' %}

{% block header %}
{% endblock %}

{% block contest %}
active
{% endblock %}

{% block content %}

		{% if done == True %}
		<div class="alert alert-success alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    ثبت نام با موفقیت انجام شد.
    </div>
		{% endif %}

			<table class="table table-hover">
				<thead>
					<tr>
						<th class="text-center">#</th>
						<th>نام آزمون</th>
						<th class="text-center">زمان	</th>
						<th class="text-center">مدت	ثبت‌نام</th>
						<th class="text-center">مدت	آزمون</th>
						<th class="text-center">شرکت‌کننده‌ها</th>
						<th></th>	
					</tr>
				</thead>
				<tbody>
					{% for contest in contests %}
					<tr>
						<td class="text-center">{{ forloop.counter }}</td>
						<td>{{ contest.contest_name }}</td>
						<td class="text-center">{{ date|get_item:contest.id }}<br>{{ time|get_item:contest.id }}</td>
						<td class="text-center">{{ dur|get_item:contest.id }}</td>
						<td class="text-center">{{ need|get_item:contest.id }}</td>
						<td class="text-center">{{ contest.reg_count }}</td>
						<td class="text-center" >
							<form class="form-inline" method="post" action="{% url 'cms_register:contests' %}">
								{% csrf_token %}
								<div class="form-group">
									<input type="hidden" name="cid" value="{{ contest.id }}">
									<div class="btn-group" role="group" aria-label="">
										{% if ended|get_item:contest.id %}
											<a href="{% url 'cms_register:ranking' contest.id %}" class="btn btn-info" {% if not contest.ranking_file %} disabled="dis" {% endif %}>رده‌بندی</a>
										{% endif %}
										{% if expired|get_item:contest.id %}
											{% if contest.unofficial_ranking_file %}
											<a href="{% url 'cms_register:unranking' contest.id %}" class="btn btn-primary">رده‌بندی تمرینی</a>
											{% endif %}
										{% else %}
											{% if not request.user.is_authenticated %}
												<a href="{% url 'cms_register:login' %}" class="btn btn-warning">وارد شوید</a>
											{% elif not registered|get_item:contest.id %}
												<button type="submit" name="register" value="register" class="btn btn-success">ثبت‌نام</button>
											{% else %}
												<a href="{{ contest.contest_url }}" class="btn btn-primary" {% if not registered|get_item:contest.id %} disabled="disabled" {% endif %}>ورود</a>

											{% endif %}
										{% endif %}
									</div>
										{% if not expired|get_item:contest.id %}
											<div id="clock{{ contest.id }}" style="margin-top: 10%"></div>
											<script type="text/javascript">
											var rem_time = new Date().getTime() + {{ cdown|get_item:contest.id }} * 1000;
											$('#clock{{ contest.id }}').countdown(rem_time, function(event) {
											  	var totalHours = event.offset.totalDays * 24 + event.offset.hours;
											    $(this).html('مهلت ثبت‌نام: '+toPersianNum(event.strftime(totalHours + ':%M:%S')));
												});
											</script>
										{% endif %}
								</div>
							</form>								
						</td>	
					</tr>
					{% endfor %}
				</tbody>
			</table>
    
{% endblock %}

cms_register/templates/cms_register/index.html
{% extends 'cms_register/base.html' %}

{% block content %}
      <h1 style="text-align: center">آزمون‌های عملی</h1>
			<br>
      <p class="lead">
				{% for Ann in Announce %}
					<blockquote>{{ Ann.announce_text }}</blockquote>
				{% endfor %}
			</p>
{% endblock %}

cms_register/templates/cms_register/login.html
{% extends 'cms_register/base.html' %}

{% block header %}
{% endblock %}

{% block login %}
active
{% endblock %}

{% block content %}

		{% if Error == True %}
		<div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    نام‌کابری یا رمزعبور غلط است.
    </div>
		{% endif %}
	<div class="panel panel-primary">
		<div class="panel-heading">ورود</div>
  	<div class="panel-body">
      <form class="form-horizontal" method="post" action="{% url 'cms_register:login' %}">
		{% csrf_token %}
				<div class="form-group">
					<label for="username" class="col-sm-3 control-label">نام کاربری</label>
					<div class="col-sm-9">
						<input type="text" class="form-control" id="usernamse" name="username" placeholder="نام کاربری">
					</div>
				</div>
				<div class="form-group">
					<label for="password" class="col-sm-3 control-label">رمز عبور</label>
					<div class="col-sm-9">
						<input type="password" class="form-control" id="password" name="password" placeholder="رمز عبور">
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
						<button type="submit" class="btn btn-primary">ورود	</button>
					</div>
				</div>
			</form>
		</div>
	</div>

{% endblock %}

cms_register/templates/cms_register/ranking.html
{% extends 'cms_register/base.html' %}

{% block contest %}
active
{% endblock %}

{% block content %}
	{% if not exp and not request.user.is_staff %}
		<div class="alert alert-warning" role="alert">
		<strong>دسترسی مجاز نیست.</strong><br><br>مسابقه هنوز تمام نشده است.
		</div>
	{% elif error %}
		<div class="alert alert-info" role="alert">
		<strong>دسترسی مجاز نیست.</strong><br><br>رده‌بندی هنوز وجود ندارد.
		</div>	
	{% else %}
			<h3 class="text-center">{{ contest.contest_name }}</h3>
			<br>
			<table class="table table-bordered">
				<thead>
					<tr>
						{% for t in head %}
							<th class="text-center">{{ t }} {% if un %} - غیررسمی {% endif %}</th>
						{% endfor %}
					</tr>
				</thead>
				<tbody>
					{% for user in users %}
					<tr>
						<td class="text-center">{{ user.rank }}</td>
						<td>{{ user.name }}</td>
						{% for sub in user.subs %}
							<td class="text-center" style="background-color:rgb({{ sub.green }},255,{{ sub.green }})">{{ sub.score }}</td>
						{% endfor %}
					</tr>
					{% endfor %}
				</tbody>
			</table>
    {% endif %}
{% endblock %}

cms_register/templates/cms_register/recover_form.html
{% extends 'cms_register/base.html' %}

{% block header %}
{% endblock %}

{% block login %}
active
{% endblock %}

{% block content %}

		{% if Error == True %}
		<div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    نام‌کابری یا رمزعبور غلط است.
    </div>
		{% endif %}
	<div class="panel panel-primary">
		<div class="panel-heading">ورود</div>
  	<div class="panel-body">
      <form class="form-horizontal" method="post" action="{% url 'cms_register:login' %}">
		{% csrf_token %}
				<div class="form-group">
					<label for="username" class="col-sm-3 control-label">نام کاربری</label>
					<div class="col-sm-9">
						<input type="text" class="form-control" id="usernamse" name="username" placeholder="نام کاربری">
					</div>
				</div>
				<div class="form-group">
					<label for="password" class="col-sm-3 control-label">رمز عبور</label>
					<div class="col-sm-9">
						<input type="password" class="form-control" id="password" name="password" placeholder="رمز عبور">
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
						<button type="submit" class="btn btn-primary">ورود	</button>
					</div>
				</div>
			</form>
			<a href={% url "password_reset_recover" %}>پسورد خود را فراموش کرده اید؟</a>
		</div>
	</div>

{% endblock %}

cms_register/templates/cms_register/register.html
{% extends 'cms_register/base.html' %}

{% block header %}
{% endblock %}

{% block reg %}
active
{% endblock %}

{% block content %}

	{% if ok %}
	<div class="alert alert-success alert-dismissible fade in" role="alert">
		{% if x %}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		{% endif %}
	اطلاعات ثبت شد.</div>
	{% endif %}
	{% if not ok or x %}
	<div class="panel panel-primary">
		<div class="panel-heading">{% if x %}تنظیمات{% else %}ثبت نام{% endif %}</div>
  	<div class="panel-body">
		{% if x %}
			<p style="font-size: 14px; color : blue; padding-bottom: 1em">اگر نمی‌خواهید رمزعبور را تغییر دهید، رمزعبور و تکرار آن را خالی بگذارید.</p>
		{% endif %}
      <form class="form-horizontal" method="post" action="{% if not x %}{% url 'cms_register:register' %}{% else %}{% url 'cms_register:profile' %}{% endif %}">
		{% csrf_token %}

					{% for key in info %}
				<div class="form-group {% if error|get_item:key != '' %}has-error{% endif %}">
						<label for="{{ key }}" class="col-sm-3 control-label">{{ place|get_item:key }}</label>
						<div class="col-sm-9">
							{% if key == 'grade' %}
							<select class="form-control" id="{{ key }}" name="{{ key }}">
								  <option class="form-control" value="دهم">دهم</option>
								  <option class="form-control" value="سوم">سوم</option>
								  <option class="form-control"  value="سایر">سایر</option>
							</select>
								
							{% else %}
							<input {% if x and key == 'username' %}disabled="disabled"{% endif %} type="{{ type|get_item:key }}" class="form-control" id="{{ key }}" name="{{ key }}" placeholder="{{ place|get_item:key }}" value="{{ info|get_item:key }}">
							{% endif %}
							{% if error|get_item:key != '' %}
							 <span class="help-block">{{ error|get_item:key }}</span>
							{% endif %}
						</div>
				</div>
					{% endfor %}
				<div class="form-group {% if caper %}has-error{% endif %}">
					<div class="col-sm-offset-3 col-sm-9">
					{% if caper %}
						<span class="help-block">لازم است که ربات نباشید.</span>
					{% endif %}
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
						<button type="submit" class="btn btn-primary">ثبت</button>
					</div>
				</div>
			</form>
		</div>
	</div>
	{% endif %}
{% endblock %}